
spring:
  datasource:
    url: jdbc:h2:mem:productsdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver


provider:
  products:
    host: https://retoolapi.dev/AZPGnS/
    path: products