server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migrations
    enabled: true
  datasource:
    url: jdbc:h2:mem:productsdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: 'health,info'
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          UP: 200
          UNKNOWN: 500
          DOWN: 500
          OUT_OF_SERVICE: 503

provider:
  products:
    host: https://retoolapi.dev/AZPGnS/
    path: products